---
title: "test_github.Rmd"
output: html_document
date: "2023-01-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#Install Packages

library(tidyverse)
library(readxl)
library(janitor)
```

```{r}
Spring_2020_raw_test <- read_excel("Spring 2020 - Percent Cover - Raw Data DNET.xlsx", sheet = "Sheet1", col_names = TRUE)
Spring_2020_raw <- read_excel("Spring 2020 - Percent Cover - Raw Data DNET.xlsx", sheet = "Sheet1", col_names = FALSE) 
Spring_2021_raw <- read_excel("Spring 2021 - Percent Cover - Raw Data DNET.xlsx", sheet = "Sheet1", col_names = FALSE)
Spring_2022_raw <- read_excel("Spring 2022 - Percent Cover - Raw Data DNET.xlsx", sheet = "Sheet1", col_names = FALSE)

```


```{r}
Spring_data_raw_pre <- bind_rows(Spring_2020_raw, Spring_2021_raw, Spring_2022_raw)
Spring_data_raw_pre <- Spring_data_raw_pre %>% 
  row_to_names(row_number(1)) %>% ## change the first row to be the name of the column
  rename(Transect = `Transect #`, Hits = `# Hits`)%>%
  filter(Date != "Date" & Date !="mm/dd/yy")

nrow(Spring_data_raw_pre)
```


```{r}
Spring_data_raw <- Spring_data_raw_pre %>%
  mutate(Date = as.Date(as.numeric(Date), origin = "1899-12-30"))%>%
  mutate(Distance = as.numeric(Distance), 
         Block = as.factor(Block), 
         Plot = as.factor(Plot), 
         Region = as.factor(Region), 
         Treatment = as.factor(Treatment), 
         Hits = as.numeric(Hits))%>%
  filter(is.na(Date) == FALSE)

str(Spring_data_raw)
```


```{r}
Full_Species_List_Glossary_reference_only_ <- read_excel("Full Species List Glossary (reference only).xlsx")

SpeciesKey <- Full_Species_List_Glossary_reference_only_%>%
  select(1:7)%>%
  rename(SpeciesCode =`Species Code (A-Z)`, NativeStatus = `Native/Non-Native`, CommonName = `Common Name`, SciName = `Full Scientific Name (Genus species)`)

unique(Spring_data_raw$Code)%>% write.csv(file = "DNCodes_raw.csv")
DNCodes <- read_csv("DNCodes.csv")


```


```{r}
intermediate <- Spring_data_raw%>%
  full_join(DNCodes, by = "Code")%>%
  left_join(SpeciesKey, by = "SpeciesCode")%>%
  mutate(LifeForm = case_when(is.na(LifeForm) == FALSE ~ LifeForm, TRUE ~ as.character(LifeForm)),
         CommonName = case_when(
           SpeciesCode == "L" ~ "littter",
           SpeciesCode == "B" ~ "bare ground",
           SpeciesCode == "W" ~ "coarse woody debris",
           SpeciesCode == "F" ~ "fine debris",
           SpeciesCode == "R" ~ "rock",
           SpeciesCode == "S" ~ "stem",
           SpeciesCode == "T" ~ "thatch",
           TRUE ~ as.character(CommonName)
         ),
         SciName = case_when(
           Type == "Ground" ~ CommonName,
           TRUE ~ as.character(SciName)
         )
           
)%>%
  select(-Code )%>%
  fill(Transect) # will copy the value from the row above 

HITS <- intermediate%>%
  filter(is.na(Hits) == TRUE)

```

